apply plugin: 'com.android.library'
apply plugin: 'org.jetbrains.kotlin.android'

apply from: "$rootDir/sharedGradleFiles/androidShared.gradle"
apply from: "$rootDir/sharedGradleFiles/hiltDependencies.gradle"

dependencies {
    // Androidx
    implementation(libs.androidx.annotation)
    implementation(libs.androidx.core.ktx)

    // Coroutines
    implementation(libs.coroutines.core)
}
